export const BookData = [
    {
        id: 0,
        book_name: "Chhatrapati Shivaji Maharaj",
        book_description: "Chhatrapati Shivaji will always be remembered as a brave, clever, and wise Hindu ruler. Although his resources were very limited and he did not receive formal education, with his bravery, courage, and intelligence, he confronted the mighty Mughal emperor Aurangzeb's vast army several times and increased his own power. Chhatrapati Shivaji was not only an able administrator but also a social reformer. He reconverted many people to Hinduism who had previously been converted to other religions. Shivaji was a person of great character, and he highly respected women. He severely punished those who mistreated women or committed the murder of innocent individuals. Author Bhawan Singh Rana has presented a brief account of Shivaji's courageous life journey in this book",
        book_url: "https://m.media-amazon.com/images/I/41x50XBTuJL._SY445_SX342_.jpg",
        print_length: "505 pages",
        language: " Marathi",
        author_name: "Krishanrao Arjun Kelusakar",
        price: "499",
    },
    {
        id: 1,
        book_name: "The Buddha and His Dhamma",
        book_description: "The story of prince siddhartha’s transformation from a restless man to an enlightened one enchants both kids and adults alike. This beautifully illustrated book introduces the little ones to Buddha, the enlightened one, and his ideologies. The magical combination of vibrant illustrations, simple Hind language and age-appropriate content makes this book fun and engaging for children to read. The book is rich with wisdom, knowledge and is highly enjoyable for the young readers.",
        book_url: "https://m.media-amazon.com/images/I/712aKodTXYL._SY342_.jpg",
        print_length: "  480 pages",
        language: "English",
        author_name: "Dr. B.R. Ambedkar",
        price: "250",
    },
    {
        id: 2,
        book_name: "Dr.Babasaheb Ambedkar Life & Mission",
        book_description: "This book is a full-length, up-to-date and authentic biography of the great Indian scholar and statesman, leader and Liberator and the chief architect of the Constitution of India, Dr. B. R. Ambedkar. The author, Dr. Dhananjay keer has endeavour to cast a gripping light on his words, deeds and the motives from which they sprang. The book is based on several interviews of Dr. Ambedkar taken by the author and the final craft of the book was read, checked and approved by Dr. Ambedkar himself. He had also cleared some points in relation to some events. This has increased the authenticity of the book.",
        book_url: "https://m.media-amazon.com/images/I/61G3VQWIvuL._SY466_.jpg",
        print_length: " pages",
        language: "English",
        author_name: "Dr. Dhananjay keer",
        price: "642",
    },
    {
        id: 3,
        book_name: "Veer Savarkar ",
        book_description: "As the intellectual fountainhead of the ideology of Hindutva, which is in political ascendancy in India today, Vinayak Damodar Savarkar is undoubtedly one of the most contentious political thinkers and leaders of the twentieth century. Accounts of his eventful and stormy life have oscillated from eulogizing hagiographies to disparaging demonization. The truth, as always, lies somewhere in between and has unfortunately never been brought to light. Savarkar and his ideology stood as one of the strongest and most virulent opponents of Gandhi, his pacifist philosophy and the Indian National Congress.",
        book_url: "https://m.media-amazon.com/images/I/812ao-DsKzL._SY342_.jpg",
        print_length: "642 pages",
        language: "English",
        author_name: "vikram Sampath",
        price: "749",
    },
    {
        id: 4,
        book_name: "HALF GIRLFRIEND",
        book_description: "Half Girlfriend is a story of Bihari boy Madhav, a Hindi speaking Bihari who falls in love with Riya, an influential Delhi girl on the campus of prestigious St. Stephen’s College. Madhav belongs to middle class family, while Riya is from higher class and both have different lifestyles. Madhav proposes her, but Riya rejects the proposal because she thinks they are good as a friend only. A romance novel for the young adults, Half Girlfriend is a story that has been set in different locations including Bihar, Delhi and New York; it revolves around a boy who comes from Bihar in India and his deep longing to dazzle out the girl he is in love with. According to the author, the book is meant for the and reveals the utter dissatisfaction and language problems a young man from Bihar, who speaks Bhojpuri and knows little about the ways of big cities, had to wade through as he got admitted at St. Stephen’s College in the national capital, a place that signified sophistication. He falls for a rich, smart and high-class girl from the city. Although the girl never fully accepts this relationship, she nevertheless gives a nod to be his half girlfriend.",
        book_url: "https://m.media-amazon.com/images/I/712HEn9SNwL._AC_UY327_FMwebp_QL65_.jpg",
        print_length: "280 pages",
        language: "English",
        author_name: "Chetan Baghat",
        price: "169",
    },
    {
        id: 5,
        book_name: "One Indian Girl",
        book_description: "The novel's main character is a girl named Radhika, who is making arrangements for her wedding to Brijesh Gulati, a software engineer in San Francisco. Throughout the book, Radhika reflects on her life growing up in Delhi as a studious introverted girl from a middle-class family. She also introduces her outgoing older sister Aditi, and reveals her tendency to communicate with her inner a judgmental voi.",
        book_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjjIibrgm2C1y4Z5P7iOs1jRXHG6q96wuhjg&s",
        print_length: "200 pages",
        language: "English",
        author_name: "Chetan Bhagat",
        price: "299",
    },
    {
        id: 6,
        book_name: "The Girl in Room 105",
        book_description: "Shoot all the bluejays you want, if you can hit 'em, but remember it's a sin to kill a mockingbird.' A lawyer's advice to his children as he defends the real mockingbird of Harper Lee's classic novel - a black man falsely charged with the rape of a white girl. Through the young eyes of Scout and Jem Finch, Harper Lee explores with exuberant humour the irrationality of adult attitudes to race and class in the Deep South of the 1930s. The conscience of a town steeped in prejudice, violence and hypocrisy is pricked by the stamina of one man's struggle for justice. But the weight of history will only tolerate so much. To Kill a Mockingbird is a coming-of-age story, an anti-racist novel, a historical drama of the Great Depression and a sublime example of the Southern writing tradition.",
        book_url: "https://m.media-amazon.com/images/I/61bLUqwvv6L._SY466_.jpg",
        print_length: "356 pages",
        language: "English",
        author_name: "Chetan Bhagt",
        price: "162",
    },
    {
        id: 7,
        book_name: "Enter At Your Own Risk",
        book_description: "Get ready for an adrenaline-pumping ride through six spine-chilling tales in Enter At Your Own Risk . As you flip through the pages, you'll encounter vengeful spirits, malevolent entities, and ancient curses lurking around every corner. Once you step into this world of fear, there's no going back. Brace yourself for a heart-pounding adventure into the unknown, where terror reigns supreme and reality blurs before your eyes.",
        book_url: "https://m.media-amazon.com/images/I/61T+85su6mL._SY342_.jpg",
        print_length: "220 pages",
        language: "English",
        author_name: "Anirban Bhattacharyya ",
        price: "183",
    },
    {
        id: 8,
        book_name: "Ghosts of The Silent Hills: Stories based on true haunting",
        book_description: "The dead do not rest till they get what they want. You have arrived in the hills. In here, you are surrounded by dense, menacing forests, enveloped in a deadly silence... You never know what lurks here in the Cold, dark night. Do not walk alone after sunset in the hills. A beautiful woman in white haunts the Lonely pathways, looking to enchant and ensnare men... All the people who died in accidents here... They say you hear their screams at night. And the deserted lodges sitting amidst lush greenery and calm streams... Spirits lie in wait here, ready to prey on the living. There are sceptics who did not heed these warnings. They tried to rationalize what they saw, what they felt. But when they came face to face with the beings that they believed didn’t exist, they couldn’t run away anymore... Ghosts of the silent hills is a collection that will make your nights a little scarier, encompassing the very best spine-chilling stories based on true hauntings",
        book_url: "https://m.media-amazon.com/images/I/71NUqTiGrOL._SY342_.jpg",
        print_length: "312 pages",
        language: "English",
        author_name: "Anita Krishan ",
        price: "179",
    },
    {
        id: 9,
        book_name: "The Mussoorie Murders",
        book_description: "Mussoorie, 1909. The ghastly murder of Margaret Maynard Liddell in a hotel room locked from the inside shocks the public. Its ripples reach Sir Arthur Conan Doyle and Rudyard Kipling, who can only guess the identity of the killer but never prove it.Around sixty years later, a wealthy heiress is found similarly murdered in the queen of the hills. The needle of suspicion points to an old housekeeper, an estranged brother, an aloof husband, and a fraud godman and his acolyte, for each of them has a motive to kill her.Avijit Sikdar, an Oxford-returned detective and a fan of Doyle and Kipling’s writings, gets a whiff of the case and begins his hunt for the elusive killer while trying to piece together the connection between the two crimes.Join Sikdar and Kipling on this thrilling and page-turning adventure across two timelines as they untangle the mystery of the murder in a locked ro",
        book_url: "https://m.media-amazon.com/images/I/91tVxoFevzL._SY342_.jpg",
        print_length: "295 pages",
        language: "English",
        author_name: "Divyaroop Bhatnagar",
        price: "188",
    },
    {
        id: 10,
        book_name: "Gitanjali ",
        book_description: "The collection by Tagore, originally written in Bengali, comprises 157 poems, many of which have been turned into songs or Rabindrasangeet. The original Bengali collection was published on 4 August 1910. The translated version Gitanjali: Song Offerings was published in November 1912 by the India Society of London which contained translations of 53 poems from the original Gitanjali, as well as 50 other poems extracted from Tagore’s Achalayatana, Gitimalya, Naivadya, Kheya, and more. Overall, Gitanjali: Song Offerings consists of 103 prose poems of Tagore’s own English translations.[3] The poems were based on medieval Indian lyrics of devotion with a common theme of love across most poems. Some poems also narrated a conflict between the desire for materialistic possessions and spiritual longing.",
        book_url: "https://m.media-amazon.com/images/I/51e94ABR7HL._SY445_SX342_.jpg",
        print_length: " 167 pages",
        language: "Hindi",
        author_name: "Rabindranath Tagore",
        price: "142",
    },
    {
        id: 11,
        book_name: "Gita Rahasya",
        book_description: "This beautiful edition, contains the essence of the Vedas and the Upanishadas, and is a sure guide of the way to perfect happiness, here as well as hereafter. It preaches the threefold way of knowledge, Action and Devotion, leading to the highest good of mankind. This book is a golden embossed edition of the classic and is suitable for festive gifting as well as keeping in ones own personal library. Its soft matt finish and embossed gold gives it a rich look topped up with enriching content",
        book_url: "https://m.media-amazon.com/images/I/71FcUflUjSL._SY342_.jpg",
        print_length: " 720 pages",
        language: "Hindi",
        author_name: " Bal Gangadhar Tilak",
        price: "383",
    },
    {
        id: 12,
        book_name: "Bhagavad Gita ",
        book_description: "The Bhagavadgita, or 'Sacred Song', holdsan assured place among the world's greatscriptures. In fourteen hundred lines of verse,the relationship of man with God - and theintense joy of divine love - are celebrated,in a language that is precise and beautiful.The Gita is a tale of action, taking the form of adialogue between Arjuna and Krishna on the eveof a battle. Krishna teaches the fearful Arjuna theneed for action and the requirement that he - likeall mankind - take his place in the world in loveand faith. Only through the search for God andthe Absolute will the true self be discovered.This edition of the Bhagavadgita offersthe Sanskrit text as well as Radhakrishnan'sEnglish translation and a commentary thathas become a classic. His clear understandingof the profound wisdom contained within theGita ensures an equally clear vision of itspowerful and eternal message, one thatcannot fail to touch the minds and spiritsof all those who reach for it.",
        book_url: "https://m.media-amazon.com/images/I/51YKQ4-5pIL._SY445_SX342_.jpg",
        print_length: "480 pages",
        language: "English",
        author_name: "S. Radhakrishnan",
        price: "324",
    },
    {
        id: 13,
        book_name: "Mahabharata",
        book_description: "Veda Vyasa's legendary epic needs no introduction. The Mahabharata is a story of brotherhood, deceit, love and sacrifice. It is also the setting for The Gita, Lord Krishna's discourse on dharma. This 42­comic box set is a comprehensive retelling of the greatest epic ever. Volume one is about the early days in Hastinapur and the birth of Duryodhana's hate for his cousins the Pandavas. The story continues to the Pandavas' escape from the burning palace of shellac to their eventual marriage to Draupadi. Volume two describes the events of the fateful game of dice which ends in the Pandavas losing their entire kingdom to the victorious Kauravas. The Pandavas are sent into exile for 13 years. Volume three encapsulates the great battle of Kurukshetra. The bitter war is fought for eighteen days ending, with Krishna?s help, in victory for the Pandavas. Collector?s Editions! Something extra for the devoted readers Amar Chitra Katha also offers special editions of their books. These editions contain never­seen­before pages, and come elegantly hard­bound All you can read! ",
        book_url: "https://m.media-amazon.com/images/I/81pbYiVZCEL._AC_UY327_FMwebp_QL65_.jpg",
        print_length: "1206 pages",
        language: "English",
        author_name: "	Vyasa",
        price: "498",
    },
    {
        id: 14,
        book_name: "Meiro Shree Krishna Leela Poorshottam Bhagwan",
        book_description: "This books brings spirituality to worldly life and suggests how to face the challenges and compulsions of human life with faith and devotion toward the Supreme, without becoming lost in egoistic pursuits and selfish actions. Know that you are not the body but the spiritual Self.",
        book_url: "https://m.media-amazon.com/images/I/71O-mt3waGL._SY342_.jpg",
        print_length: " 960 pages",
        language: "Hindi",
        author_name: "A. C. Bhaktivedanta Swami Prabhupada",
        price: "292",
    },
    {
        id: 15,
        book_name: "Shri Ramayana",
        book_description: "The epic Ramayana is the story of the great Shri Rama, a god in human form—from his birth and childhood, his marriage to Sita, the daughter of King Janak, to the politics that led to his exile, the war he waged against Raavan, who had kidnapped his wife, and finally to his glorious victory and reinstatement as the ruler of Ayodhya. Valmiki's great epic, the Ramayana, is a must-read for all! Other titles by M I Rajasve: Ashtavakra Mahagita, Dashrath Nandan-Dashanan Gatha, Chanakya Charitam Aur Akhand Rashtriya Ekta, Ashwatthama ki Amar Mani, Ashwatthama ka Abhishap.",
        book_url: "https://m.media-amazon.com/images/I/810Y-6-ouCL._SY342_.jpg",
        print_length: "340 pages",
        language: "Hindi",
        author_name: "MI Rajasve",
        price: "231",
    },
    {
        id: 16,
        book_name: "Mahayoddha Kalki",
        book_description: "Mahayoddha Kalki: Sword of Shiva is an epic fantasy novel by Kevin Missal that takes readers on a thrilling adventure through ancient India. This book is the third in the Mahayoddha Kalki series and features gripping action, compelling characters, and a richly imagined world. A must-read for fans of fantasy and mythology.",
        book_url: "https://m.media-amazon.com/images/I/710-B3pVSLL._SY342_.jpg",
        print_length: " 368 pages",
        language: "English",
        author_name: "Kevin Missal",
        price: "281",
    }
]